---
resources:
- name: source-code-resource
  type: git
  source:
    uri: {{source-code-resource-uri}}
    private_key: {{github-private-key}}

- name: pipeline-resource
  type: git
  source:
    uri: {{pipeline-resource-uri}}
    branch: {{pipeline-resource-branch}}
    private_key: {{github-private-key}}
    
jobs:
- name: job-build-and-verify
  plan:
  - get: source-code-resource
    trigger: true
  - get: pipeline-resource
  - task: build-and-verify
    file: pipeline-resource/tasks/maven-build.yml
    input_mapping: {source-code: source-code-resource, pipeline: pipeline-resource}
