---
platform: linux
image_resource:
  type: docker-image
  source: {repository: concourse/buildroot, tag: curl}

inputs:
  - name: artifact-to-deploy
  - name: pipeline
outputs:
  - name: manifest-to-deploy

run:
  path: pipeline/tasks/generate-manifest.sh
